version: "3"

services:
  sonarqube:
    # This image was used to fix my personal config (Mac OS M1 Pro)
    # If you are not using an M1 machine simply change the image property to the following:
    # image: sonarqube:community
    # Source: https://docs.sonarqube.org/latest/setup-and-upgrade/install-the-server/#:~:text=Example%20Docker%20Compose%20configuration
    image: davealdon/sonarqube-with-docker-and-m1-macs
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: